language: java

# From 7.4, NetBeans needs Java 7
jdk:
    - oraclejdk8
    - oraclejdk7
    - openjdk7
before_install:
    - travis_retry sudo add-apt-repository --yes ppa:hansjorg/rust
    - travis_retry sudo apt-get update
install:
    - travis_retry sudo apt-get install --assume-yes rust-nightly
    - travis_retry mvn dependency:go-offline
    - mvn package -DskipTests
script: mvn package
