language: java

jdk:
  - oraclejdk8
  - oraclejdk9
env:
  - RUST_CHANNEL=stable
  - RUST_CHANNEL=nightly
matrix:
    allow_failures:
      - env: RUST_CHANNEL=nightly
      - jdk: oraclejdk9
before_install:
  - "curl https://sh.rustup.rs -sSf > rustup && chmod +x rustup"
  - "./rustup -y"
  - "export PATH=$PATH:~/.cargo/bin"
  - rustc --version
install:
  - rustup toolchain install ${RUST_CHANNEL}
  - rustup override set ${RUST_CHANNEL}
  - rustc --version
  - mvn --batch-mode package -DskipTests
script: mvn --batch-mode package
