language: java

# From 7.4, NetBeans needs Java 7
# We've decided to use Java 8
jdk:
    - oraclejdk8
    - oraclejdk7
    - openjdk7
before_install:
    - sudo add-apt-repository --yes ppa:hansjorg/rust
    - sudo apt-get update
install:
    - sudo apt-get install --assume-yes rust-nightly
    - mvn dependency:go-offline
script: mvn package
