version: '{build}'
os: Windows Server 2012
platform:
    - x86
    - x64
environment:
    matrix:
        - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
install:
  - cinst maven
  - ps: Start-FileDownload "https://raw.githubusercontent.com/Fireforge/rustup-powershell/master/rustup.ps1"
  - ps: ./rustup.ps1
  - rustc -V
  - cargo -V
build_script:
  - mvn clean package -DskipTests
test_script:
  - mvn clean package
cache:
  - C:\maven\
  - C:\Users\appveyor\.m2
