version: '{build}'
os: Windows Server 2012
platform:
    - x86
    - x64
environment:
    matrix:
        - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
install:
  - cinst maven
  - ps: src/build/scripts/rustup.ps1
build_script:
  - mvn clean package -DskipTests
test_script:
  - mvn clean package
cache:
  - C:\Users\appveyor\.m2
