version: '{build}'
os: Windows Server 2012
environment:
    matrix:
        - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
        - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
install:
  - ps: choco install maven
  - ps: src/build/scripts/rustup.ps1
  - ps: $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
  - mvn --version
  - rustc --version
  - cargo --version
build_script:
  - mvn --batch-mode clean package -DskipTests
test_script:
  - mvn --batch-mode clean package
after_test:
  - ps: |
        Write-Host "Uploading test reports"
        $web_client = New-Object 'System.Net.WebClient'
        $url = "https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)"
        Get-ChildItem "target\surefire-reports" -Filter *.xml | Foreach-Object {
            $path = (Resolve-Path $_.FullName)
            Write-Host "Uploading $($path) to $($url)..."
            $web_client.UploadFile($url, $path)
        }
artifacts:
    - path: target/rust-libs/*

cache:
  - C:\Users\appveyor\.m2
