version: '{build}'
os: Windows Server 2012
platform:
    - x86
    - x64
environment:
    matrix:
        - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
install:
  - ps: choco install maven
  - ps: src/build/scripts/rustup.ps1
  - ps: $env:Path
  - ps: $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
  - ps: $env:Path
  - mvn --version
  - rustc --version
  - cargo --version
build_script:
  - mvn clean package -DskipTests
test_script:
  - mvn clean package
cache:
  - C:\Users\appveyor\.m2
