version: '{build}'
os: Windows Server 2012
platform:
    - x86
      #- x64
environment:
    matrix:
        - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
install:
  - ps: choco install maven
  - ps: $env:Path
  - SET PATH=%PATH%;C:\bin\apache-maven-3.2.5\bin
  - mvn --version
  - ps: Start-FileDownload 'https://static.rust-lang.org/dist/rust-nightly-i686-pc-windows-gnu.exe'
  - rust-nightly-i686-pc-windows-gnu.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - rustc --version
  - cargo --version
build_script:
  - mvn clean package -DskipTests
test_script:
  - mvn clean package
cache:
  - C:\Users\appveyor\.m2
